DROP TABLE IF EXISTS Restaurants.Organization
CREATE TABLE Restaurants.Organization
(
	OrganizationID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	OrganizationName NVARCHAR(128) NOT NULL,
	DateFounded DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET())
)